version: '2'
checks:
  argument-count:
    enabled: false
  method-complexity:
    enabled: false
  method-lines:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
