builds:
  - main: ./cmd/manael/main.go
    binary: manael
    ldflags:
      - -extldflags "-static"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
changelog:
  skip: true
dockers:
  - build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.authors=Manael Authors
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.description=Manael is a simple HTTP proxy for processing images.
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.url=https://manael.org/
      - --label=org.opencontainers.image.version={{.Version}}
    image_templates:
      - ghcr.io/manaelproxy/{{ .ProjectName }}:latest
      - ghcr.io/manaelproxy/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
      - ghcr.io/manaelproxy/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
    dockerfile: Dockerfile
    ids:
      - manael
