env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/manael/main.go
    binary: manael
    ldflags:
      - -extldflags "-static"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
archives:
  - replacements:
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^v\d+(?:\.\d+){0,2}$'
dockers:
  - image_templates:
      - 'manael/{{ .ProjectName }}:latest'
      - 'ghcr.io/manaelproxy/{{ .ProjectName }}:latest'
      - 'manael/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
      - 'ghcr.io/manaelproxy/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
      - 'manael/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}'
      - 'ghcr.io/manaelproxy/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}'
    dockerfile: Dockerfile
    binaries:
      - manael
