version: 2

aliases:
  - &defaults
    docker:
      - image: circleci/golang:1.10.3-stretch
    working_directory: /go/src/manael.org/x/manael

  - &attach_workspace
    attach_workspace:
      at: /go/

  - &persist_to_workspace
    persist_to_workspace:
      root: /go/
      paths:
        - ./src/github.com/*/*/
        - ./src/manael.org/x/manael/

  - &install_system_dependencies
    run:
      name: Install system dependencies
      command: |
        sudo apt-get update
        sudo apt-get install -y libwebp-dev

  - &test_steps
      steps:
        - *attach_workspace

        - *install_system_dependencies

        - run: go test -v ./...

jobs:
  fetch:
    <<: *defaults
    steps:
      - checkout

      - run: go get -v -t -d ./...

      - *persist_to_workspace

  test-go1.10:
    <<: *defaults
    <<: *test_steps

  test-go1.9:
    <<: *defaults
    docker:
      - image: circleci/golang:1.9.7-stretch
    <<: *test_steps

  test-go1.8:
    <<: *defaults
    docker:
      - image: circleci/golang:1.8.7-stretch
    <<: *test_steps

  build:
    <<: *defaults
    steps:
      - *attach_workspace

      - *install_system_dependencies

      - run: go build ./cmd/manael

workflows:
  version: 2
  build:
    jobs:
      - fetch
      - test-go1.10:
          requires:
            - fetch
      - test-go1.9:
          requires:
            - fetch
      - test-go1.8:
          requires:
            - fetch
      - build:
          requires:
            - test-go1.10
            - test-go1.9
            - test-go1.8
