version: 2

aliases:
  - &defaults
    docker:
      - image: circleci/golang:1.12-stretch
    environment:
      GO111MODULE: 'on'
    working_directory: /go/src/manael.org/x/manael

  - &install_system_dependencies
    run:
      name: Install system dependencies
      command: |
        sudo apt-get update
        sudo apt-get install -y libwebp-dev

  - &test_steps
    steps:
      - *install_system_dependencies

      - checkout

      - run: go mod download
      - run: go test -v ./...

jobs:
  setup:
    <<: *defaults
    steps:
      - *install_system_dependencies

      - checkout

      - run: go vet ./...

  test-go1.12:
    <<: *defaults
    <<: *test_steps

  test-go1.11:
    <<: *defaults
    docker:
      - image: circleci/golang:1.11-stretch
    <<: *test_steps

  build:
    <<: *defaults
    steps:
      - *install_system_dependencies

      - checkout

      - setup_remote_docker

      - run: curl -sL https://git.io/goreleaser | bash -s -- --snapshot

  release:
    <<: *defaults
    environment:
      CGO_CFLAGS: -I/tmp/libwebp/include
      CGO_LDFLAGS: -L/tmp/libwebp/lib -lwebp
      GO111MODULE: 'on'
    steps:
      - checkout

      - setup_remote_docker

      - name: Login on Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Install libwebp
        run: |
          mkdir -p /tmp/src
          cd /tmp/src
          wget -O libwebp.tar.gz https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.0.3.tar.gz
          tar -xzf libwebp.tar.gz -C /tmp/src
          rm libwebp.tar.gz
          cd /tmp/src/libwebp-1.0.3
          ./configure --prefix /tmp/libwebp
          make -j4
          make install

      - name: Release
        run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build:
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/
      - test-go1.12:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
      - test-go1.11:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test-go1.12
            - test-go1.11
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v\d+(?:\.\d+){0,2}$/
            branches:
              ignore: /.*/
