"$schema" = "./node_modules/wrangler/config-schema.json"

name = 'manael-website'
main = './src/index.ts'
compatibility_date = '2026-04-20'

[build]
command = 'pnpm build'

[assets]
directory = './public'
not_found_handling = '404-page'
binding = 'ASSETS'
run_worker_first = ["/x/manael", "/x/manael/*"]
