name: Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['!*']

env:
  GORELEASER_VERSION: 1.21.1

jobs:
  goreleaser-check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: GoReleaser Check
        uses: goreleaser/goreleaser-action@v5
        with:
          args: check
          version: ${{ env.GORELEASER_VERSION }}
