name: Release

on:
  pull_request:
    branches:
      - '!*'
  push:
    branches:
      - '!*'
    tags:
      - 'v*'

env:
  LIBAOM_VERSION: 3.1.0
  LIBWEBP_VERSION: 1.0.3

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - name: Login on Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Login on GHCR
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yasm

      - name: Install libwebp
        run: |
          mkdir -p /tmp/src
          cd /tmp/src
          wget -O libwebp.tar.gz https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-${LIBWEBP_VERSION}.tar.gz
          tar -xzf libwebp.tar.gz -C /tmp/src
          rm libwebp.tar.gz
          cd /tmp/src/libwebp-${LIBWEBP_VERSION}
          ./configure --prefix /tmp/libwebp
          make -j4
          make install

      - name: Install libaom
        run: |
          mkdir -p /tmp/src
          cd /tmp/src
          wget -O libaom.tar.gz https://storage.googleapis.com/aom-releases/libaom-${LIBAOM_VERSION}.tar.gz
          mkdir -p /tmp/src/libaom-${LIBAOM_VERSION}
          tar -xzf libaom.tar.gz -C /tmp/src/libaom-${LIBAOM_VERSION}
          rm libaom.tar.gz
          mkdir -p /tmp/src/aom_build
          cd /tmp/src/aom_build
          cmake /tmp/src/libaom-${LIBAOM_VERSION} -DCMAKE_INSTALL_PREFIX=/tmp/libaom
          make -j4
          make install

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_CFLAGS: -I/tmp/libwebp/include -I/tmp/libaom/include
          CGO_LDFLAGS: -L/tmp/libwebp/lib -lwebp -L/tmp/libaom/lib -laom -lm
