name: Release

on:
  pull_request:
    branches:
      - '!*'
  push:
    branches:
      - '!*'
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Login on Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Login on GHCR
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Install libwebp
        run: |
          mkdir -p /tmp/src
          cd /tmp/src
          wget -O libwebp.tar.gz https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.0.3.tar.gz
          tar -xzf libwebp.tar.gz -C /tmp/src
          rm libwebp.tar.gz
          cd /tmp/src/libwebp-1.0.3
          ./configure --prefix /tmp/libwebp
          make -j4
          make install

      - name: Install libaom
        run: |
          mkdir -p /tmp/src
          cd /tmp/src
          wget -O libaom.tar.gz https://storage.googleapis.com/aom-releases/libaom-3.1.0.tar.gz
          tar -xzf libaom.tar.gz -C /tmp/src/libaom-3.1.0
          rm libaom.tar.gz
          mkdir -p /tmp/src/aom_build
          cd /tmp/src/aom_build
          cmake /tmp/src/libaom-3.1.0
          make -j4
          make install

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_CFLAGS: -I/tmp/libwebp/include
          CGO_LDFLAGS: -L/tmp/libwebp/lib -lwebp
