name: Release

on:
  pull_request:
    branches:
      - '!*'
  push:
    branches:
      - '!*'
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Install libwebp
        run: |
          mkdir -p /tmp/src
          cd /tmp/src
          wget -O libwebp.tar.gz https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.0.3.tar.gz
          tar -xzf libwebp.tar.gz -C /tmp/src
          rm libwebp.tar.gz
          cd /tmp/src/libwebp-1.0.3
          ./configure --prefix /tmp/libwebp
          make -j4
          make install

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
          CGO_CFLAGS: -I/tmp/libwebp/include
          CGO_LDFLAGS: -L/tmp/libwebp/lib -lwebp
