name: Release

on:
  pull_request:
    branches:
    - '!*'
  push:
    branches:
    - '!*'
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Login on Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Install libwebp
      run: |
        mkdir -p /tmp/src
        cd /tmp/src
        wget -O libwebp.tar.gz https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.0.3.tar.gz
        tar -xzf libwebp.tar.gz -C /tmp/src
        rm libwebp.tar.gz
        cd /tmp/src/libwebp-1.0.3
        ./configure --prefix /tmp/libwebp
        make -j4
        make install

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: curl -sL https://git.io/goreleaser | bash
